# Generated by Django 3.2.23 on 2024-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0002_auto_20240417_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_estimate_items',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
