# Generated by Django 3.2.23 on 2024-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_auto_20240418_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_estimate_items',
            name='hsn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_estimate_items',
            name='sac',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
