# Generated by Django 3.2.23 on 2024-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_auto_20240418_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_sales_order_items',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
