# Generated by Django 3.2.23 on 2024-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0007_auto_20240419_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_retainer_invoice_items',
            name='SAC',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
