# Generated by Django 3.2.23 on 2024-04-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_alter_fin_retainer_invoice_customer_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_retainer_invoice',
            name='Customer_gst_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
