# Generated by Django 3.2.23 on 2024-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0010_alter_fin_retainer_invoice_customer_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_retainer_invoice',
            name='Customer_gst_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
