# Generated by Django 3.2.23 on 2024-04-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0012_auto_20240419_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_retainer_invoice_comments',
            name='Ret_Invoice',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice_history',
            name='Ret_Invoice',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice_items',
            name='Ret_Inv',
        ),
    ]
