# Generated by Django 3.2.23 on 2024-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0014_auto_20240419_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_delivery_challan_items',
            name='sac',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
