# Generated by Django 3.2.23 on 2024-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_fin_delivery_challan_items_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_recurring_invoice_items',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
