# Generated by Django 3.2.23 on 2024-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0016_fin_recurring_invoice_items_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_purchase_order_items',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
