# Generated by Django 3.2.23 on 2024-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0019_auto_20240420_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_creditnote_items',
            name='sac',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
